# Site Configuration

theme: default
lang: "en"

# No plugins for now
plugins: []

# (Optional) Google Analytics
google_analytics_id: ""

# HTML Title
title: "Liam (Moein) Manesh’s Links"

# Avatar image path (replace with your headshot)
avatar: "./images/profile.jpeg"

# Name section
name: "Liam (Moein) Manesh"

# Tagline: focuses on distributed systems, Go, and your newsletter
tagline: >-
  Staff Software Engineer | Go Enthusiast & Editor of GolangNugget Newsletter

## Core Links
links:
  - link:
      icon: "fa-solid fa-calendar"
      text: "Schedule a Call"
      url: "https://calendly.com/liam-manesh"
      alt: "Schedule a call with me"
      title: "Schedule time with me"
      target: "_blank"
  - link:
      icon: "fa-solid fa-newspaper"
      text: "GolangNugget Newsletter"
      url: "https://golangnugget.com"
      alt: "GolangNugget Newsletter"
      title: "Weekly insights on Go"
      target: "_blank"
  - link:
      icon: "fa-brands fa-linkedin"
      text: "LinkedIn"
      url: "https://www.linkedin.com/in/liam-manesh/"
      alt: "Liam’s LinkedIn"
      title: "Connect with me on LinkedIn"
      target: "_blank"
  - link:
      icon: "fa-brands fa-github"
      text: "GitHub"
      url: "https://github.com/moeinxyz"
      alt: "Liam’s GitHub"
      title: "Explore my Go & system projects"
      target: "_blank"      
  - link:
      icon: "fa-solid fa-envelope"
      text: "liam {at} mane [dot] sh"
      alt: "Liam’s Email"
      title: "Connect with me on Email"

## Social Icons
socials:
  - social:
      icon: "fa-brands fa-twitter"
      url: "https://twitter.com/liammanesh"
      title: "Follow me on Twitter"
      alt: "Liam’s Twitter"
      target: "_blank"
  - social:
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/liam-manesh/"
      title: "Follow me on LinkedIn"
      alt: "Liam’s LinkedIn"
      target: "_blank"
## Footer
footer: >
  Dive deep into Go and distributed systems with the GoLangNugget newsletter.

copyright: >
    © 2025 <a href="https://mane.sh" target="_blank">Liam Manesh</a>. Hosted on GitHub Pages.